# TCL File Generated by Component Editor 18.1
# Tue Feb 05 12:29:51 EST 2019
# DO NOT MODIFY


# 
# basic_avmm_bridge_rdv "basic_avmm_bridge_rdv" v1.0
#  2019.02.05.12:29:51
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module basic_avmm_bridge_rdv
# 
set_module_property DESCRIPTION "Basic AVMM Bridge with Read Data Valid"
set_module_property NAME basic_avmm_bridge_rdv
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME basic_avmm_bridge_rdv
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL basic_avmm_bridge_rdv
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file basic_avmm_bridge_rdv.sv SYSTEM_VERILOG PATH basic_avmm_bridge_rdv.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL basic_avmm_bridge_rdv
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file basic_avmm_bridge_rdv.sv SYSTEM_VERILOG PATH basic_avmm_bridge_rdv.sv


# 
# parameters
# 
add_parameter ADDRESS_WIDTH INTEGER 1
set_parameter_property ADDRESS_WIDTH DEFAULT_VALUE 1
set_parameter_property ADDRESS_WIDTH DISPLAY_NAME ADDRESS_WIDTH
set_parameter_property ADDRESS_WIDTH TYPE INTEGER
set_parameter_property ADDRESS_WIDTH UNITS None
set_parameter_property ADDRESS_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk ENABLED true
add_interface_port clk clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
add_interface_port reset areset reset Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end ENABLED true
add_interface_port conduit_end avm_clk clk Output 1
add_interface_port conduit_end avm_areset areset Output 1
add_interface_port conduit_end avm_address address Output ADDRESS_WIDTH
add_interface_port conduit_end avm_waitrequest waitrequest Input 1
add_interface_port conduit_end avm_read read Output 1
add_interface_port conduit_end avm_write write Output 1
add_interface_port conduit_end avm_readdata readdata Input 32
add_interface_port conduit_end avm_writedata writedata Output 32
add_interface_port conduit_end avm_readdatavalid readdatavalid Input 1


# 
# connection point avmm
# 
add_interface avmm avalon end
set_interface_property avmm addressUnits WORDS
set_interface_property avmm associatedClock clk
set_interface_property avmm associatedReset reset
set_interface_property avmm bitsPerSymbol 8
set_interface_property avmm maximumPendingReadTransactions 1
set_interface_property avmm maximumPendingWriteTransactions 0
set_interface_property avmm readLatency 0
set_interface_property avmm ENABLED true
add_interface_port avmm avs_address address Input ADDRESS_WIDTH
add_interface_port avmm avs_waitrequest waitrequest Output 1
add_interface_port avmm avs_read read Input 1
add_interface_port avmm avs_write write Input 1
add_interface_port avmm avs_readdata readdata Output 32
add_interface_port avmm avs_writedata writedata Input 32
add_interface_port avmm avs_readdatavalid readdatavalid Output 1

